### ISSUE TITLE
FrequencyByMonth array seems additive rather than per month

### ISSUE THREAD

**Issue by werdnanoslen** [jhinkel/SenseMaking#1]
FrequencyByMonth should return an array of 12 elements, one frequency for each month. However, it seems the function is returning an array where each element is that month plus the previous month. That is, I'd expect to see something like [0, 0, 3, 2, 0, 5, 0, 1, 0, 0, 1, 2], but instead it seems to return something like [0, 0, 3, 5, 5, 10, 10, 11, 11, 11, 12, 14]. (Compare the pattern to the first example array).

**Comment by jhinkel** [comment]
I'll look at it
